/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";
import { Layout } from "../components/Layout/Layout";
import { Hero } from "../components/Hero/Hero";
import { DesignSection } from "../components/DesignSection/DesignSection";
import { StepsSection } from "../components/StepsSection/StepsSection";
import { TestimonialsSection } from "../components/TestimonialsSection/TestimonialsSection";
import { ProductSection } from "../components/ProductSection/ProductSection";
import { PrintSection } from "../components/PrintSection/PrintSection";
import { BookTypesSection } from "../components/BookTypesSection/BookTypesSection";
import { FAQSection } from "../components/FAQSection/FAQSection";
import { InfoSection } from "../components/InfoSection/InfoSection";

export default component$(() => {
  return (
    <Layout>
      <Hero />
      <DesignSection />
      <StepsSection />
      <TestimonialsSection />
      <ProductSection />
      <PrintSection />
      <BookTypesSection />
      <FAQSection />
      <InfoSection />
    </Layout>
  );
});
