/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const BookTypesSection = component$(() => {
  const bookTypes = [
    { title: "Coffee Book" },
    { title: "Baby Bo﻿ard Book" },
    { title: "Mem﻿ory Book" },
    { title: "Wedding Book" },
    { title: "Portfolio Book" },
    { title: "Cook﻿book" },
    { title: "Yearbo﻿ok" },
    { title: "Corpor﻿ate Book" },
    { title: "Luxury Wedding Book" },
    { title: "Fabric Style Book" },
  ];

  return (
    <section class="flex flex-col items-center mt-32 w-full text-lg font-semibold text-black max-w-[1253px] max-md:mt-10 max-md:max-w-full">
      <h2 class="self-stretch text-3xl font-bold text-center text-zinc-800 max-md:max-w-full">
        The perfect b﻿ook for you to tell your story.
      </h2>
      <div class="flex flex-wrap gap-4 items-center mt-12 w-full tracking-normal text-center max-md:mt-10">
        {bookTypes.map((book, index) => (
          <div
            key={index}
            class="flex flex-col flex-1 shrink justify-center self-stretch my-auto whitespace-nowrap basis-0"
          >
            <div class="flex w-full rounded-md aspect-square bg-zinc-300 min-h-[238px]"></div>
            <p class="mt-6 w-full">{book.title}</p>
          </div>
        ))}
      </div>
      <button class="gap-2.5 self-stretch px-4 py-3 mt-12 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[136px] max-md:mt-10">
        Start creating
      </button>
    </section>
  );
});
