/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";
import { Header } from "./Header";
import { HeroSection } from "./HeroSection";
import { GallerySection } from "./GallerySection";
import { DiscoverWaySection } from "./DiscoverWaySection";
import { GiftSection } from "./GiftSection";
import { PrintOptionsSection } from "./PrintOptionsSection";
import { CalendarTypesSection } from "./CalendarTypesSection";
import { FAQSection } from "./FAQSection";
import { InfoSection } from "./InfoSection";
import { Footer } from "./Footer";
import { CustomCalenderSection } from "./CustomCalenderSection";
import { UpgradeSection } from "./UpgradeSection";
import { CtaSection } from "./CtaSection";
import { CalendarSpecialities } from "./CalendarSpecialities";
import { CalendarPreview } from "./CalendarPreview";
import { TestimonialsSection } from "./TestimonialsSection";
import { MobileCreativeSection } from "./MobileCreativeSection";

export const CalendarLayout = component$(() => {
  return (
    <div class="flex overflow-hidden flex-col bg-white">
      <Header />
      <main class="flex flex-col md:gap-20 gap-20">
        <HeroSection />
        <CustomCalenderSection />
        <CalendarSpecialities />
        <GallerySection />
        <DiscoverWaySection />
        <CalendarPreview />
        <TestimonialsSection />
        <GiftSection />
        <PrintOptionsSection />
        <CalendarTypesSection />
        <UpgradeSection />
        <CtaSection />
        <MobileCreativeSection />
        <FAQSection />
        <InfoSection />
      </main>
      <Footer />
    </div>
  );
});
