/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const DesignSection = component$(() => {
  return (
    <section class="flex flex-col items-center px-11 mt-20 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div class="flex flex-col items-center w-full max-w-[1256px] max-md:max-w-full">
        <div class="flex flex-col max-w-full w-[713px]">
          <h2 class="text-3xl font-bold text-zinc-800 max-md:max-w-full">
            Designs for your stories. E﻿ndless Possibilities
          </h2>
          <nav class="flex flex-wrap gap-10 items-center self-center mt-3 text-base font-semibold text-neutral-400 max-md:max-w-full">
            <a href="#" class="self-stretch my-auto text-pink-600">
              Travel
            </a>
            <a href="#" class="self-stretch my-auto">
              Wedd﻿ing
            </a>
            <a href="#" class="self-stretch my-auto">
              F﻿amily
            </a>
            <a href="#" class="self-stretch my-auto">
              Si﻿mple
            </a>
            <a href="#" class="self-stretch my-auto">
              Year In Review
            </a>
            <a href="#" class="self-stretch my-auto">
              A﻿ll
            </a>
          </nav>
        </div>
        <div class="flex flex-wrap gap-7 items-start self-stretch mt-6 w-full max-md:max-w-full">
          {[1, 2, 3, 4].map((index) => (
            <div key={index} class="flex flex-col grow shrink w-[136px]">
              <div class="flex bg-zinc-300 h-[170px] min-h-[170px] w-[170px]"></div>
              <div class="flex mt-7 bg-zinc-300 h-[170px] min-h-[170px] w-[170px]"></div>
            </div>
          ))}
          <div class="flex grow shrink bg-zinc-300 h-[371px] min-w-[240px] w-[430px]"></div>
        </div>
        <button class="gap-2.5 self-stretch px-4 py-3 mt-6 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[196px]">
          Explore Travel Themes
        </button>
      </div>
    </section>
  );
});
