/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";
import { MainLayout } from "../components/MainLayout";

export default component$(() => {
  return <MainLayout />;
});
