/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const Footer = component$(() => {
  const features = [
    {
      title: "Price Promise",
      description: "Lowest Price Guaranteed",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f615f38049caaa0d691dab15b2ab7519907e285452aac1e07c78fb7143a9cd22?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      title: "1 Mil + Custom Gifts",
      description: "Sold in 2023",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/da6cd20e0227bf2a19264f25d342781f85651ea44c134b881e356ba1857afbab?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      title: "High Rated Service",
      description: "Over 5M+ Happy Customers",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1438da376774f1b9866299bc92a0ed95eb963fd7a29c2005b3c986a15d2e5915?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      title: "Shop with Confidence",
      description: "100% Satisfaction Guarantee",
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b9d9faa20a6d3d3841b96f114438be75399d56dcc4eebfc53236273888f2bb6c?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
  ];

  const footerLinks = [
    {
      title: "PRICING",
      links: [
        "Payment Methods",
        "Shipping Policy",
        "Shipping Rates",
        "Bulk Ordering",
      ],
    },
    {
      title: "PHOTO TIPS",
      links: ["Blog", "Photo Quality", "Image Resolution"],
    },
    {
      title: "ABOUT US",
      links: [
        "Why Printerpix?",
        "About Us",
        "Testimonials",
        "Terms & Conditions",
        "Affiliates",
      ],
    },
    {
      title: "CUSTOMER CARE",
      links: [
        "Contact Us",
        "Where's My Order",
        "Privacy Policy",
        "Returns Policy",
        "Frequently Asked Questions",
        "Video Tutorials",
      ],
    },
  ];

  return (
    <footer class="flex relative flex-col mt-32 w-full max-md:mt-10 max-md:max-w-full">
      <div class="flex z-0 flex-col justify-between self-center pb-12 max-w-full text-black min-h-[174px] w-[1255px]">
        <div class="flex flex-wrap gap-10 justify-center items-center pt-12 pr-px w-full border-t border-zinc-400 max-md:max-w-full">
          {features.map((feature, index) => (
            <div
              key={index}
              class="flex grow shrink gap-3 items-center self-stretch my-auto min-w-[240px] w-[221px]"
            >
              <img
                loading="lazy"
                src={feature.icon}
                alt={feature.title}
                class="object-contain shrink-0 self-stretch my-auto aspect-[1.01] w-[73px]"
              />
              <div class="flex flex-col items-center self-stretch my-auto min-w-[240px] w-[243px]">
                <h3 class="pb-3.5 max-w-full text-lg font-bold w-[243px] max-md:pr-5">
                  {feature.title}
                </h3>
                <p class="z-10 pb-2 mt-2 max-w-full text-sm w-[243px] max-md:pr-5">
                  {feature.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
      <div class="flex z-0 flex-wrap gap-9 justify-center items-center py-10 pr-24 pl-24 w-full text-xl text-white bg-indigo-800 border-b border-zinc-400 min-h-[177px] max-md:px-5 max-md:max-w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a8e8175c89be2e3ba71bba9dac35bd7bfc23987fda871f2f44fc6f487ec5d2f?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
          alt="Sustainability icon"
          class="object-contain shrink-0 self-stretch my-auto aspect-square w-[97px]"
        />
        <p class="flex-1 shrink self-stretch my-auto basis-0 max-md:max-w-full">
          Your item is sustainably made, always. Each item we produce is printed
          with non-toxic inks and crafted under fair labour conditions. Plus,
          for every tree you plant at checkout, we plant another – all while
          keeping our offices 100% paperless.
        </p>
      </div>
      <div class="flex z-0 flex-col justify-center items-center px-14 py-7 w-full text-white bg-indigo-800 border-b border-zinc-400 max-md:px-5 max-md:max-w-full">
        <div class="flex flex-wrap gap-10 justify-center items-center max-md:max-w-full">
          <div class="flex flex-col self-stretch my-auto min-h-[98px] min-w-[240px] w-[353px]">
            <h2 class="flex-1 text-4xl font-bold">Need help?</h2>
            <p class="flex-1 mt-3 text-xl">
              We will complete your project for you:
            </p>
          </div>
          <div class="flex flex-wrap gap-6 self-stretch my-auto text-xl text-center min-h-[167px] min-w-[240px] max-md:max-w-full">
            <div class="flex flex-col items-center w-40">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3c4834e93ea6f4b3dd50ccd13e8f905bd2530e64f77dccbe79f83d71379fa432?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
                alt="Connect to agent icon"
                class="object-contain aspect-square w-[60px]"
              />
              <p class="mt-6">Connect to agent</p>
            </div>
            <div class="flex flex-col items-center w-[156px]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/3a5f5e908d27a828575e4c8555f36298ccc7dc41b59cb0d33d3311dd66ecc572?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
                alt="Request callback icon"
                class="object-contain aspect-square w-[60px]"
              />
              <p class="mt-6">Request callback</p>
            </div>
            <div class="flex flex-col items-center whitespace-nowrap min-w-[240px]">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/af62bae9e44bb0dff1ab9002468c7b34165e7b65ebea9f5a28e225a16098a8e9?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
                alt="Email icon"
                class="object-contain aspect-square w-[60px]"
              />
              <p class="mt-6">@projecthelp@printerpix.co.uk</p>
            </div>
          </div>
        </div>
      </div>
      <div class="flex z-0 flex-col justify-center items-center py-14 pr-24 pl-24 w-full bg-indigo-800 max-md:px-5 max-md:max-w-full">
        <div class="flex flex-wrap gap-10 justify-between max-w-full min-h-[236px] w-[1251px]">
          <div class="flex flex-col justify-center min-w-[240px] w-[530px] max-md:max-w-full">
            <div class="flex flex-col w-full text-white max-md:max-w-full">
              <h2 class="text-4xl font-bold max-md:max-w-full">
                Enjoy 40% OFF Your First Order
              </h2>
              <p class="mt-6 text-xl max-md:max-w-full">
                When you join our newsletter! Be the first to receive exclusive
                offers, inspiration & more.
              </p>
            </div>
            <form class="flex flex-wrap gap-2.5 mt-6 max-w-full text-base w-[491px]">
              <label for="email" class="sr-only">
                Enter Email Address
              </label>
              <input
                type="email"
                id="email"
                placeholder="Enter Email Address"
                class="grow px-4 py-2 bg-white rounded border border-solid border-zinc-300 text-zinc-400 w-fit max-md:pr-5"
              />
              <button
                type="submit"
                class="overflow-hidden z-10 gap-2.5 self-stretch px-7 py-2 font-bold text-center text-white bg-pink-600 rounded min-h-[38px] max-md:px-5 max-md:mr-0"
              >
                subscribe now
              </button>
            </form>
          </div>
          <div class="flex flex-col justify-center pl-5 text-white border-l border-zinc-400 min-w-[240px]">
            <h3 class="text-3xl font-bold">Rated 4.5/5</h3>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/b37c8996fcbaee3a11916dd6474809147453dd3c353961ccfe3c7872b2488252?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
              alt="Trustpilot rating"
              class="object-contain mt-5 max-w-full aspect-[4.74] w-[361px]"
            />
            <p class="mt-5 text-xl">Based on 34,038 reviews from Trustpilot</p>
          </div>
        </div>
      </div>
      <nav class="flex z-0 w-full bg-indigo-800 min-h-[774px] max-md:max-w-full">
        <div class="flex absolute right-24 z-0 flex-wrap gap-10 justify-between items-start max-w-full bottom-[557px] left-[95px] w-[1249px]">
          {footerLinks.map((section, index) => (
            <div key={index} class="text-base font-bold text-white">
              <h4 class="text-xl mb-2">{section.title}</h4>
              {section.links.map((link, linkIndex) => (
                <a key={linkIndex} href="#" class="block">
                  {link}
                </a>
              ))}
            </div>
          ))}
          <div class="flex flex-col justify-between w-[204px]">
            <div class="flex-1 text-base font-bold text-white">
              <h4 class="text-xl mb-2">CONTACT US</h4>
              <p>+44 0208 839 0854</p>
              <p>contactus@printerpix.co.uk</p>
            </div>
            <div class="text-base font-bold text-white mt-4">FOLLOW US:</div>
            <div class="flex gap-2 justify-between items-start w-full mt-2">
              {[
                "https://cdn.builder.io/api/v1/image/assets/TEMP/27d6c44e9797c62b785b9fc3221de0e2f822ecee7449d649494a884a43caebad?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
                "https://cdn.builder.io/api/v1/image/assets/TEMP/507e6b7a929a374febca89c28aac7a5b9250860dac1441cbc916026462c2c3e9?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
                "https://cdn.builder.io/api/v1/image/assets/TEMP/e89a941c0c835761963970f280089ffe9267d9be6ab839d7b59e4347ea9fcce9?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
                "https://cdn.builder.io/api/v1/image/assets/TEMP/7a5cbdfd2a61ed9a77bba100aac47945f3d8fdab576ae78b8bf188fca0a5b29f?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
                "https://cdn.builder.io/api/v1/image/assets/TEMP/a6b0624eca4907f9e0b7acc7fd70ec8f0c98758d9273aac3250d20765085135e?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
              ].map((icon, index) => (
                <a
                  key={index}
                  href="#"
                  aria-label={`Social media link ${index + 1}`}
                >
                  <img
                    loading="lazy"
                    src={icon}
                    alt=""
                    class="object-contain shrink-0 aspect-square w-[35px]"
                  />
                </a>
              ))}
            </div>
          </div>
        </div>
      </nav>
      <div class="flex absolute left-2/4 z-0 flex-col items-center max-w-full text-base text-white -translate-x-2/4 bottom-[283px] translate-y-[0%] w-[1250px]">
        <div class="w-full border border-solid border-zinc-400 min-h-[1px] max-md:max-w-full"></div>
        <h4 class="self-center mt-14 font-bold text-center max-md:mt-10">
          PRINTERPIX WORLDWIDE:
        </h4>
        <div class="flex flex-wrap gap-10 justify-between items-center self-center mt-14 max-w-full w-[1126px] max-md:mt-10">
          {[
            {
              country: "United States",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/9c2ffce398fc1baf2355c00d761dfb879cec7f71697db89bd5c80897f2fecc6c?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "United Kingdom",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/b4b14bcc3f13cc5530878f5d46ca402323382eeaa376133e5245349f9a5b20cf?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "France",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/3a9f9e670997ad34c2f5f39cbe17a4ebff2c6b72fb30a7a296dca4efded723db?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "Italy",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/7359e300ba18f53a75e7e86e826860a04611416a1c69d00613377c05aff31952?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "Spain",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/7b2f2e8c367bf90d5888c300c91657a23bcc4c5f1bb274b9a2bdf22e104fcebb?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "Germany",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/db7bd86819760a007b5994a9ec98d6ad3bffe1fcef9b902e360ff8c639b6d486?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
            {
              country: "Netherland",
              flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/097bc15868b3840f0516de79edcfde6d8f2e56b0e3c62ac639053555c6ba7562?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
            },
          ].map((item, index) => (
            <div
              key={index}
              class="flex gap-4 justify-center items-center self-stretch my-auto"
            >
              <img
                loading="lazy"
                src={item.flag}
                alt={`${item.country} flag`}
                class="object-contain shrink-0 self-stretch my-auto aspect-square w-[33px]"
              />
              <p class="self-stretch my-auto">{item.country}</p>
            </div>
          ))}
        </div>
        <div class="mt-14 w-full border border-solid border-zinc-400 min-h-[1px] max-md:mt-10 max-md:max-w-full"></div>
      </div>
      <p class="absolute bottom-10 left-24 z-0 self-start h-4 text-xs text-white right-[1196px]">
        Copyright © 2022 Printerpix
      </p>
      <div class="absolute bottom-10 z-0 self-start h-4 text-xs text-white left-[1204px] right-[79px]">
        <a href="#" class="mr-4">
          Terms of Service
        </a>
        <a href="#">Privacy</a>
      </div>
      <div class="flex absolute z-0 flex-wrap gap-10 justify-between items-center max-w-full text-xs text-white bottom-[111px] inset-x-[95px] w-[1250px]">
        <div class="flex flex-col items-center self-stretch my-auto min-w-[240px] w-[340px]">
          <p>Secured Payment:</p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/498fb8a0889ea7ebf4112998617a177605d676c56616a944eb69f3cd1b54b549?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
            alt="Secured payment methods"
            class="object-contain mt-6 max-w-full aspect-[5.95] w-[340px]"
          />
        </div>
        <div class="shrink-0 self-stretch my-auto w-0 border border-solid border-zinc-400 h-[104px]"></div>
        <div class="flex flex-col items-center self-stretch my-auto min-w-[240px] w-[324px]">
          <p>Certified Delivery:</p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/469fa85c1109df56b2faf379404f8d8fe8f3b0c660975962140ae7e034b9a652?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
            alt="Certified delivery partners"
            class="object-contain mt-9 max-w-full aspect-[9.52] w-[324px]"
          />
        </div>
        <div class="shrink-0 self-stretch my-auto w-0 border border-solid border-zinc-400 h-[104px]"></div>
        <div class="flex flex-col items-center self-stretch my-auto w-40">
          <p>Secured by:</p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4681868036fcf0ca2e94b696946ba940fc2c9952103c725397c311b37342a08e?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
            alt="Security certification"
            class="object-contain mt-9 w-40 max-w-full aspect-[4.22]"
          />
        </div>
        <div class="shrink-0 self-stretch my-auto w-0 border border-solid border-zinc-400 h-[104px]"></div>
        <div class="flex flex-col items-center self-stretch my-auto w-40">
          <p>Trusted by:</p>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/36183996ebc9b2e9e241e3bbeb3fd572d746f04930f29e0021b318b528ea1fb3?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
            alt="Trusted by certification"
            class="object-contain mt-7 w-40 max-w-full aspect-[4.1]"
          />
        </div>
      </div>
    </footer>
  );
});
