/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const BookTypesSection = component$(() => {
  const bookTypes = [
    { name: "Coffee Book", rows: 1 },
    { name: "Baby Board Book", rows: 1 },
    { name: "Memory Book", rows: 1 },
    { name: "Wedding Book", rows: 1 },
    { name: "Portfolio Book", rows: 1 },
    { name: "Cookbook", rows: 2 },
    { name: "Yearbook", rows: 2 },
    { name: "Corporate Book", rows: 2 },
    { name: "Luxury Wedding Book", rows: 2 },
    { name: "Fabric Style Book", rows: 2 },
  ];

  return (
    <section class="flex flex-col items-center mt-32 w-full text-lg font-semibold text-black max-w-[1253px] max-md:mt-10 max-md:max-w-full">
      <h2 class="self-stretch text-3xl font-bold text-center text-zinc-800 max-md:max-w-full">
        The perfect book for you to tell your story.
      </h2>
      {[1, 2].map((row) => (
        <div
          key={row}
          class="flex flex-wrap gap-4 items-center mt-12 w-full tracking-normal text-center max-md:mt-10"
        >
          {bookTypes
            .filter((type) => type.rows === row)
            .map((type, index) => (
              <div
                key={index}
                class="flex flex-col flex-1 shrink justify-center self-stretch my-auto whitespace-nowrap basis-0"
              >
                <div class="flex w-full rounded-md aspect-square bg-zinc-300 min-h-[238px]"></div>
                <p class="mt-6 w-full">
                  {type.name.split(" ").map((word, i) => (
                    <span key={i}>
                      {word}
                      {i < type.name.split(" ").length - 1 && <br />}
                    </span>
                  ))}
                </p>
              </div>
            ))}
        </div>
      ))}
      <a
        href="#start-creating"
        class="gap-2.5 self-stretch px-4 py-3 mt-12 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[136px] text-center max-md:mt-10"
      >
        Start creating
      </a>
    </section>
  );
});
