/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const BookTypesSection = component$(() => {
  const bookTypes = [
    "Coffee Book",
    "Baby Bo﻿ard Book",
    "Mem﻿ory Book",
    "Wedding Book",
    "Portfolio Book",
  ];

  return (
    <section class="flex flex-col items-center pr-24 pl-24 mt-20 w-full text-lg font-semibold text-black max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <h2 class="self-stretch text-3xl font-bold text-center text-zinc-800 max-md:max-w-full">
        The perfect b﻿ook for you to tell your story.
      </h2>
      {[...Array(2)].map((_, rowIndex) => (
        <div
          key={rowIndex}
          class="flex flex-wrap gap-4 items-center mt-12 max-w-full tracking-normal text-center w-[1253px] max-md:mt-10"
        >
          {bookTypes.map((type, index) => (
            <div
              key={index}
              class="flex flex-col flex-1 shrink justify-center self-stretch my-auto whitespace-nowrap basis-0"
            >
              <div class="flex w-full rounded-md aspect-square bg-zinc-300 min-h-[237px]"></div>
              <p class="mt-6 w-full">
                {type.split(" ").map((word, i) => (
                  <span key={i}>
                    {word}
                    {i === 0 && <br />}
                  </span>
                ))}
              </p>
            </div>
          ))}
        </div>
      ))}
      <button class="gap-2.5 self-stretch px-4 py-3 mt-12 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[136px] max-md:mt-10">
        Start creating
      </button>
    </section>
  );
});
