/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const Footer = component$(() => {
  return (
    <footer class="flex flex-col mt-8 w-full text-black max-w-[1246px] max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0c93f90bc12dc23dbefa9770374765a615049ce81224211fb779811fee253ad?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
        alt="Footer banner"
        class="object-contain mt-28 w-full aspect-[1000] max-w-[1255px] max-md:mt-10 max-md:max-w-full"
      />
      <div class="flex flex-col mt-8 w-full max-md:max-w-full">
        <section class="flex flex-col w-full text-zinc-900 max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-zinc-900">
              Online Photo Printing Service
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            Digital photo printing with Printerpix is easy. It only takes a few
            simple steps to order photo prints online. You can even crop and
            adjust the orientation of your photo by taking advantage of our
            design tool. Whether you want to showcase a stunning landscape or
            capture a special moment with loved ones, our design tool gives you
            full control over the final result. With Printerpix, you can order
            your photo prints in less than five minutes, from any device.
          </p>
        </section>
        <section class="flex flex-col mt-8 w-full max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-black">
              Order Photo Prints Online
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            Once you've selected all your photos to be printed and chosen the
            right size, make sure to add premium extras to make your photo
            prints really stand out. Consider removing our logo for a clean,
            professional look. Want to make the colours pop? Choose our 6-colour
            HD printing option for richer, more saturated tones. When you're
            satisfied with your choices, finalise your order by filling in your
            shipping and payment details. Your online photo prints will be
            delivered to your door in no time.
          </p>
          <h3 class="mt-4 font-bold">
            Creative Display Ideas for Your Photo Prints
          </h3>
          <p class="mt-2">
            Nature-Inspired Branch Display: Use a piece of wood or a branch to
            hang your photo prints. Secure your prints with twine and clips onto
            the branch for a unique and rustic display.
          </p>
        </section>
        <section class="flex flex-col mt-8 w-full max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-black">
              Vintage Ladder Collage:
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            Give an old ladder a new purpose by repurposing it into a creative
            photo display. Lean the ladder against a wall and hang your photo
            prints from the rungs using strings or ribbons. This
            vintage-inspired setup adds character and charm, turning an everyday
            object into a stunning showcase for your memories.
          </p>
        </section>
        <section class="flex flex-col mt-8 w-full max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-black">
              Insta-Worthy Photo Wall:
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            Create a photo wall by arranging your online photo prints in a
            visually appealing and eclectic manner. Combine frames, canvas
            prints, and even photo tiles for a diverse yet cohesive display.
            This trendsetting approach turns your wall into a personalised art
            gallery that reflects your unique style.
          </p>
        </section>
        <section class="flex flex-col mt-8 w-full max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-black">
              Memory Jar Centrepiece:
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            Place your photo prints in a decorative glass jar or vase. This
            unique centrepiece not only showcases your memories but also
            provides an elegant and charming focal point for a coffee table or
            mantelpiece.
          </p>
        </section>
        <section class="flex flex-col mt-8 w-full max-md:max-w-full">
          <h2 class="text-lg font-semibold tracking-normal max-md:max-w-full">
            <span class="text-base font-bold tracking-normal leading-6 text-black">
              Affordable Digital Photo Printing & Gifting
            </span>
          </h2>
          <p class="mt-3 text-base tracking-normal max-md:max-w-full">
            In the age of phones, digital cameras, and cloud storage, our
            devices are overflowing with countless photos that often go
            unnoticed. Transforming these digital memories into tangible
            keepsakes by printing them on exquisite glossy paper brings them to
            life and places them right at your fingertips.
            <br />
            <br />
            Our classic photo prints add a retro-inspired touch to your photos.
            With space to customise with a printed or written caption, our photo
            booth strips become an even more cherished keepsake. What sets our
            photo posters apart is their large format – perfect for displaying
            those larger-than-life moments. Whichever format you choose, rest
            assured that you've found the cheapest photo prints at the highest
            quality.
            <br />
            <br />
            In the era of high-quality digital photo printing, your memories can
            now be preserved forever with ease. We understand the importance of
            sharing your memories with loved ones – and we know they'll always
            love receiving photo prints from you. From days at the beach to
            milestone birthdays, we offer a cost-effective solution to bring
            your pictures to life. Finding the cheapest photo prints couldn't be
            easier. Print your latest adventure or that Christmas party they
            couldn't attend, and send the joy through the mail!
          </p>
        </section>
      </div>
    </footer>
  );
});
