/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const Hero = component$(() => {
  return (
    <section class="flex flex-col mt-8 w-full max-md:max-w-full">
      <div class="flex flex-col justify-center items-start px-24 py-10 w-full text-sm bg-neutral-200 min-h-[274px] max-md:px-5 max-md:max-w-full">
        <div class="flex flex-col max-w-full w-[339px]">
          <h1 class="text-3xl font-bold text-zinc-800">
            Tell your Stories with <br />a Photo Book
          </h1>
          <p class="mt-3 text-black">
            Starting at $14.99 <br /> Get it by Sept 23 with Express
          </p>
          <a
            href="#create-book"
            class="gap-2.5 self-stretch px-4 py-3 mt-3 w-full text-white bg-pink-500 rounded shadow-sm text-center"
          >
            Create your book
          </a>
        </div>
      </div>
      <div class="flex flex-wrap gap-10 justify-between items-center self-center px-6 py-3 mt-6 max-w-full text-indigo-800 bg-blue-200 rounded-2xl w-[1250px] max-md:px-5">
        <div class="flex flex-col self-stretch my-auto w-[153px]">
          <div class="self-start text-2xl font-bold text-center">
            🍂 🍁Fall Sale
          </div>
          <div class="mt-2 text-sm">No Code Needed.</div>
        </div>
        <div class="self-stretch my-auto text-2xl font-bold text-center">
          Up to 50% off + an extra 10%
        </div>
        <div class="self-stretch my-auto text-sm text-right">
          No Code Needed. <br /> Discount applied on checkout.
        </div>
      </div>
    </section>
  );
});
