/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const StepsSection = component$(() => {
  const steps = [
    {
      title: "Digital backups",
      description:
        "Qucikly add images from your phon﻿e, computer, social media, & Google photos.",
      img: "/images/simple-step-1.jpg",
    },
    {
      title: "Auto-Create",
      description:
        "We'll instantly organize your photos into a cohesiv﻿e, well-designed story.",
      img: "/images/simple-step-2.jpg",
    },
    {
      title: "Customize",
      description:
        "Easily change fonts, backgrounds,colors, shapes, stickers, and more.",
      img: "/images/simple-step-3.jpg",
    },
  ];

  return (
    <section class="container mx-auto mt-12 flex flex-col justify-evenly gap-8 px-4 md:px-0">
      <h2 class="text-center text-3xl font-bold text-zinc-800 max-md:max-w-full">
        Your Books in 3 Easy Steps
      </h2>
      <div class="flex w-full flex-wrap items-stretch gap-6 text-center text-black max-md:max-w-full">
        {steps.map((step, index) => (
          <div
            key={index}
            class="flex min-w-[240px] flex-1 shrink basis-0 flex-col justify-center"
          >
            <div
              class="flex min-h-[547px] w-full flex-grow bg-zinc-300"
              style={{
                backgroundImage: `url(${step.img})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            />
            <div class="mt-6 flex w-full flex-grow flex-col">
              <h3 class="text-2xl font-bold">{step.title}</h3>
              <p class="mt-3 text-sm">{step.description}</p>
            </div>
          </div>
        ))}
      </div>
      <button class="w-[136px] max-w-full gap-2.5 self-center rounded bg-pink-500 px-4 py-3 text-sm text-white shadow-sm">
        Start creating
      </button>
    </section>
  );
});
