/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const TestimonialsSection = component$(() => {
  const testimonials = [
    {
      title: "Digital backups",
      description:
        "Qucikly add images from your phone, computer, social media, & Google photos.",
    },
    {
      title: "Quality Paper",
      description:
        "Qucikly add images from your phone, computer, social media, & Google photos.",
    },
    {
      title: "Quick Delivery",
      description:
        "Qucikly add images from your phone, computer, social media, & Google photos.",
    },
  ];

  return (
    <section class="flex flex-col mt-20 text-black  container mx-auto md:px-0 px-4">
      <h2 class="text-3xl font-bold text-center text-zinc-800 max-md:max-w-full">
        Books Made with Love
      </h2>
      {[...Array(2)].map((_, rowIndex) => (
        <div
          key={rowIndex}
          class="flex gap-6 items-center mt-12 w-full text-center max-md:mt-10 max-md:max-w-full"
        >
          <div class="flex flex-wrap flex-1 shrink gap-6 justify-center items-center self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                class="flex flex-col flex-1 shrink justify-center self-stretch my-auto basis-0 min-w-[240px]"
              >
                <div class="flex self-center rounded-full aspect-square bg-zinc-300 min-h-[200px] w-[200px]"></div>
                <div class="flex flex-col mt-6 w-full">
                  <h3 class="text-2xl font-bold">{testimonial.title}</h3>
                  <p class="mt-3 text-sm">{testimonial.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ))}
      <button class="gap-2.5 self-center px-4 py-3 mt-12 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[136px] max-md:mt-10">
        Start creating
      </button>
    </section>
  );
});
