/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const Footer = component$(() => {
  const features = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4c8c89394d74e33cafda548736191b298736b89898fd7129a17a9802b325fe63?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "Price Promise",
      description: "Lowest Price Guaranteed",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/38eb4a291cce8344fe75b6c21d5a7a2f644f7ee77629162fe08c57a99c4aa732?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "1 Mil + Custom Gifts",
      description: "Sold in 2023",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/098b817b8f771d3777418c559d5407c604471a693b96de42f02f503a83c8dc5a?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "High Rated Service",
      description: "Over 5M+ Happy Customers",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d9b376195f33070fe7a9c7f7079c571f6a2f78c4ee0fdf155c7e7bda8317be8c?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "Shop with Confidence",
      description: "100% Satisfaction Guarantee",
    },
  ];

  const helpOptions = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/f5e17e124eb869e267b15609c8a00b7a3ea25a75eb327efa6d5bfe3ec62d4846?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "Connect to agent",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6200b7426d5903ede14472b85b0d26821b9dd3cd19797056228cb28f7c4f9203?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "Request callback",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/e0c79e93c744d60a005f22e6e91bf9a9cd8da0c04dcadeebb9043feb1ad6bbb1?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
      title: "@projecthelp@printerpix.co.uk",
    },
  ];

  const footerLinks = [
    {
      title: "PRICING",
      links: [
        "Payment Methods",
        "Shipping Policy",
        "Shipping Rates",
        "Bulk Ordering",
      ],
    },
    {
      title: "PHOTO TIPS",
      links: ["Blog", "Photo Quality", "Image Resolution"],
    },
    {
      title: "ABOUT US",
      links: [
        "Why Printerpix?",
        "About Us",
        "Testimonials",
        "Terms & Conditions",
        "Affiliates",
      ],
    },
    {
      title: "CUSTOMER CARE",
      links: [
        "Contact Us",
        "Where's My Order",
        "Privacy Policy",
        "Returns Policy",
        "Frequently Asked",
        "Questions",
        "Video Tutorials",
      ],
    },
  ];

  const countries = [
    {
      name: "United States",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/b84e5dce7e8f7270048e312bc30d30c1a403acc820b35ecd5f8e420334296b21?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "United Kingdom",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/d7a79a23d3c20da0ab015c2817a28faeb0c3081a5c54d72eaa068311cbe7f050?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "France",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/c75061def3b177443e26985da1a72a35b8c8494585439b30ce496ee235431d97?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "Italy",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/4e830e2b53ed63b55b3eade85d636c7c1209d82759780d8e18b9163345b24872?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "Spain",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/714c5428e2c1c4305499100f2eb9ad13e65e364e1e7b7fba66575f72ff2ca510?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "Germany",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/93d85e573db9b24558ea1f1c8bedb19cc40ffad6ed7296281e3b1507c21137d4?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
    {
      name: "Netherland",
      flag: "https://cdn.builder.io/api/v1/image/assets/TEMP/c447d3ad4d0a20a3c6563cc182a883c7fcee45c791b003b45b683a0f8b3b0235?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27",
    },
  ];

  return (
    <footer class="flex relative flex-col w-full max-md:mt-10 max-md:max-w-full">
      <div class="flex z-0 flex-wrap gap-9 justify-center items-center py-10 px-24 w-full text-xl text-white bg-indigo-800 border-b border-zinc-400 max-lg:px-8 max-md:px-4">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/1fe1f9f9ec335e222b96e6cf73444a27edf4e459da9cbf2eb4dcd6694f4b202f?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
          alt="Sustainability icon"
          class="object-contain shrink-0 aspect-square w-[97px] max-md:w-[60px] max-md:mx-auto"
        />
        <p class="flex-1 my-auto max-md:text-base max-md:text-center">
          Your item is sustainably made, always. Each item we produce is printed
          with non-toxic inks and crafted under fair labour conditions. Plus,
          for every tree you plant at checkout, we plant another – all while
          keeping our offices 100% paperless.
        </p>
      </div>
      <div class="flex z-0 flex-col items-center px-14 py-12 w-full bg-indigo-800 max-lg:px-8 max-md:px-4">
        <h2 class="text-4xl font-bold text-white text-center max-md:text-2xl">Need help?</h2>
        <p class="mt-4 text-xl text-white text-center max-md:text-lg">
          We will complete your project for you:
        </p>
        <div class="flex flex-wrap justify-center gap-10 mt-8 max-md:gap-6">
          {helpOptions.map((option, index) => (
            <div key={index} class="flex flex-col items-center w-40 max-md:w-[45%]">
              <img
                src={option.icon}
                alt={option.title}
                class="w-[60px] h-[60px] max-md:w-[40px] max-md:h-[40px]"
              />
              <p class="mt-4 text-white text-center text-lg max-md:text-base">{option.title}</p>
            </div>
          ))}
        </div>
      </div>
      <div class="flex flex-wrap gap-10 justify-between px-24 py-14 bg-indigo-800 max-lg:px-8 max-md:px-4">
        <div class="flex-1 min-w-[300px] max-md:min-w-full">
          <h2 class="text-4xl font-bold text-white max-md:text-2xl max-md:text-center">
            Up to 80% OFF Your First Order
          </h2>
          <p class="mt-4 text-xl text-white max-md:text-base max-md:text-center">
            Sign up to our newsletter to receive early access to sales...
          </p>
          <form class="flex flex-wrap gap-3 mt-6 max-md:flex-col">
            <input
              type="email"
              placeholder="Enter Email Address"
              class="flex-1 px-4 py-3 rounded min-w-[200px] max-md:w-full"
            />
            <button class="px-8 py-3 bg-pink-600 text-white rounded font-bold max-md:w-full">
              Subscribe Now
            </button>
          </form>
        </div>
        <div class="flex flex-col justify-center pl-8 border-l border-zinc-400 max-md:border-l-0 max-md:pl-0 max-md:mt-8 max-md:items-center">
          <h3 class="text-5xl font-bold text-white max-md:text-3xl">Rated 4.5/5</h3>
          <div class="flex mt-4">
            {/* Add your star rating component here */}
          </div>
          <p class="mt-4 text-white">Based on 35,645 reviews</p>
        </div>
      </div>
      <div class="bg-indigo-800 px-24 py-12 max-lg:px-8 max-md:px-4">
        <div class="grid grid-cols-4 gap-8 max-lg:grid-cols-2 max-md:grid-cols-1">
          {footerLinks.map((section, index) => (
            <div key={index} class="text-white">
              <h3 class="font-bold mb-4">{section.title}</h3>
              <ul class="space-y-2">
                {section.links.map((link, i) => (
                  <li key={i} class="hover:underline cursor-pointer">{link}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div class="mt-12 text-white max-md:text-center">
          <h3 class="font-bold mb-4">FOLLOW US:</h3>
          <div class="flex gap-4 max-md:justify-center">
            {/* Social media icons */}
          </div>
        </div>
      </div>
      <div class="bg-indigo-800 px-24 py-12 text-white max-lg:px-8 max-md:px-4">
        <h3 class="text-center font-bold mb-8">PRINTERPIX WORLDWIDE:</h3>
        <div class="flex flex-wrap justify-center gap-8 max-md:gap-4">
          {countries.map((country, index) => (
            <div key={index} class="flex items-center gap-2 min-w-[140px] max-md:min-w-[45%]">
              <img src={country.flag} alt={country.name} class="w-8 h-8" />
              <span>{country.name}</span>
            </div>
          ))}
        </div>
      </div>
      <div class="bg-indigo-800 px-24 py-8 text-white max-lg:px-8 max-md:px-4">
        <div class="grid grid-cols-3 gap-8 max-lg:grid-cols-2 max-md:grid-cols-1 max-md:gap-12">
          <div class="text-center">
            <p class="mb-4">Secured Payment:</p>
            <div class="flex flex-wrap justify-center gap-2">
              {/* Payment method icons */}
            </div>
          </div>
          <div class="text-center">
            <p class="mb-4">Certified Delivery:</p>
            <div class="flex flex-wrap justify-center gap-2">
              {/* Delivery method icons */}
            </div>
          </div>
          <div class="text-center max-lg:col-span-2 max-md:col-span-1">
            <p class="mb-4">Secured by:</p>
            <div class="flex justify-center">
              {/* Security badges */}
            </div>
          </div>
        </div>
      </div>
      <div class="bg-indigo-800 px-24 py-4 text-white text-sm max-lg:px-8 max-md:px-4 max-md:text-center">
        <div class="flex justify-between max-md:flex-col max-md:gap-2">
          <p>Copyright © 2022 Printerpix</p>
          <p>Terms of Service Privacy</p>
        </div>
      </div>
    </footer>
  );
});
