/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const TestimonialsSection = component$(() => {
  const testimonials = [
    {
      title: "Premium Covers",
      description: "Detailed craftsmanship for a high-end look & feel.",
      img: "/svg/book-cover.svg",
    },
    {
      title: "Quality Paper",
      description: "Expect vivid, precise colors on the paper of your choice.",
      img: "/svg/quality-paper.svg",
    },
    {
      title: "Add Extra Pages",
      description: "Go up to 40, 100 or 200 pages to tell your story.",
      img: "/svg/add-pages.svg",
    },
    {
      title: "Discounted Copies",
      description: "Surprise loved ones with extra copies of your book.",
      img: "/svg/discounted-copies.svg",
    },
    {
      title: "Free Templates",
      description: "Start fast with free templates you can edit in seconds.",
      img: "/svg/free-templates.svg",
    },
    {
      title: "Save Project",
      description: "Need more time? We'll save your project for 60 days.",
      img: "/svg/save-project.svg",
    },
    {
      title: "American Made",
      description: "Printed & hand-inspected in Orlando, Florida.",
      img: "/svg/american-flag.svg",
    },
    {
      title: "Speedy Shipping",
      description: "Order with Rush Shipping for 1 day delivery.",
      img: "/svg/delivery-black.svg",
    },
  ];

  return (
    <section class="container mx-auto flex  flex-col gap-8 px-4 text-black md:px-0">
      <h2 class="text-center text-3xl font-bold text-zinc-800 max-md:max-w-full">
        Books Made with Love
      </h2>
      <div class="grid lg:grid-cols-4 grid-cols-2 gap-x-4 gap-y-[46px]">
        {testimonials.map((testimonial, index) => (
          <div
            key={index}
            class="my-auto flex flex-col items-center lg:min-w-[240px] min-w-[150px] flex-1 shrink basis-0 justify-center self-stretch gap-4"
          >
            <div
              class="lg:min-h-[200px] lg:w-[200px] min-h-[150px] min-w-[150px] w-full"
              style={{
                backgroundImage: `url(${testimonial.img})`,
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            />
            <div class="flex w-full flex-col items-center gap-3 text-center">
              <h3 class="text-2xl font-bold">{testimonial.title}</h3>
              <p class="text-sm">{testimonial.description}</p>
            </div>
          </div>
        ))}
      </div>
      <button class="mt-12 md:w-[136px] w-full max-w-full gap-2.5 self-center rounded bg-pink-500 px-4 py-3 text-sm text-white shadow-sm max-md:mt-10">
        Start creating
      </button>
    </section>
  );
});
