/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const FAQSection = component$(() => {
  const faqs = [
    {
      question: "How do I order photo prints online from my phone?",
      answer:
        "You can upload pictures from your camera roll, Google Drive or connect to your social media accounts like Instagram or Facebook.",
    },
    { question: "What is photo pri﻿nting?" },
    { question: "What is the best site to print my photos?" },
    { question: "How l﻿ong does it take to receive my online photo prints?" },
  ];

  return (
    <section class="flex flex-col items-center mt-32 w-full max-w-[1256px] max-md:mt-10 max-md:max-w-full">
      <h2 class="self-stretch text-3xl font-bold text-center text-zinc-800 max-md:max-w-full">
        FAQ About Pho﻿to Prints
      </h2>
      <div class="flex flex-col mt-6 max-w-full w-[642px]">
        {faqs.map((faq, index) => (
          <div
            key={index}
            class="flex flex-col p-6 w-full bg-zinc-100 mt-5 max-md:px-5 max-md:max-w-full"
          >
            <div class="flex flex-wrap gap-10 justify-between items-center w-full text-lg font-semibold tracking-normal text-zinc-900 max-md:max-w-full">
              <h3 class="self-stretch my-auto max-md:max-w-full">
                {faq.question}
              </h3>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82f207ebba529f25e351a700830db376db844db238d3b8d825e6ec7ef933fe37?placeholderIfAbsent=true&apiKey=7f743169fed1434cba7b7dfa49538c27"
                alt="Expand icon"
                class="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
              />
            </div>
            {faq.answer && (
              <p class="mt-6 text-sm text-black rotate-[0.00002835407575880291rad] max-md:max-w-full">
                {faq.answer}
              </p>
            )}
          </div>
        ))}
      </div>
      <button class="gap-2.5 self-stretch px-4 py-3 mt-6 max-w-full text-sm text-white bg-pink-500 rounded shadow-sm w-[136px]">
        Order Prints
      </button>
    </section>
  );
});
